project:
  type: book

book:
  title: "One code to rule them all (┛ಠ_ಠ)┛彡O"
  author: "Jared Adam"
  date: "6/6/2023"
  chapters:
    - index.qmd
    - part: "The Reasoning"
      chapters:
        - a_introduction.qmd
        - b_RasATool.qmd
    - part: "The Beginnings"
      chapters: 
        - c_NewProj.qmd
        - d_functionality.qmd
        - e_CallingVariables.qmd
        - f_fancy.qmd
        - g_etiquette.qmd
    - part: "Buckle up"
      chapters: 
        - h_wrangling.qmd
    - part: "Plotting along: IN BETA"
      chapters: 
        #- i_ggplot.qmd
        - j_ggplotHW.qmd 
    - part: "Last part"
      chapters: 
        - resources.qmd
        - Endearment.qmd
    - references.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
    title-block-banner: "#9e74f1"
    toc: true
    code-block-bg: true
    code-block-border-left: "#1abcd9"
    highlight-style: atom-one
    code-copy: true
    code-fold: false
    code-overflow: wrap
    code-tools: true
    code-link: true
  pdf: 
    pdf-engine: xelatex
    documentclass: scrreprt
execute: 
  freeze: auto